export const EMAIL_TEMPLATE_ID = {
  OTP: 'OTP',
  WELCOME: 'WELCOME',
  RESET_PASSWORD: 'RESET_PASSWORD',
  EMAIL_VERIFY: 'EMAIL_VERIFY',
  UPDATE_EMAIL_VERIFY: 'UPDATE_EMAIL_VERIFY',
  INVITATION_EMAIL: 'INVITATION_EMAIL',
} as const;

export const EMAIL_TEMPLATE_RUNTIME_ID: Record<EMAIL_TEMPLATE_ID, string> = {
  OTP: process.env.RESEND_TEMPLATE_OTP_ID!,
  WELCOME: process.env.RESEND_TEMPLATE_WELCOME_ID!,
  RESET_PASSWORD: process.env.RESEND_TEMPLATE_RESET_PASSWORD_ID!,
  EMAIL_VERIFY: process.env.RESEND_TEMPLATE_EMAIL_VERIFY_ID!,
  INVITATION_EMAIL: process.env.RESEND_TEMPLATE_TEAM_INVITE_ID!,
  UPDATE_EMAIL_VERIFY: process.env.RESEND_TEMPLATE_UPDATE_EMAIL_ID!,
};

export type EMAIL_TEMPLATE_ID =
  (typeof EMAIL_TEMPLATE_ID)[keyof typeof EMAIL_TEMPLATE_ID];
